version: "3.9"
services:
  spark:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src:/app/src
      - ./mlruns:/app/mlruns
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_HOSTNAME=localhost
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "4040:4040"
    depends_on:
      - mlflow
    networks:
      - lakehouse

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlruns.db --default-artifact-root /mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    networks:
      - lakehouse

networks:
  lakehouse:
    driver: bridge